### ISSUE TITLE
怎么使用？我上传了但是好像并没有成功，能否给个教程。

### ISSUE THREAD

**Issue by uuuuuuzeus** [htchina/openfire-webshell#1]
怎么使用？我上传了但是好像并没有成功，能否给个教程。

**Comment by htchina** [comment]
> 怎么使用？我上传了但是好像并没有成功，能否给个教程。

**Comment by htchina** [comment]
注意看图，图已经标出来上传的shell在哪一个位置了

**Comment by 13230046860** [comment]
![image](https://user-images.githubusercontent.com/48279042/88266713-3b7e8f00-cd02-11ea-855e-6d5c42c74b38.png)
![image](https://user-images.githubusercontent.com/48279042/88266728-446f6080-cd02-11ea-92e5-6ea64c535951.png)
![image](https://user-images.githubusercontent.com/48279042/88266763-5224e600-cd02-11ea-955c-6faad8be59bd.png)
我直接在上传插件的位置，直接上传了jcore.jar插件，然后提示上传成功，但是在用户组界面，也就是你标注的那个位置，并没有出现该插件，我直接复制的路径打开http://ip:9090/plugins/jcore/married.jsp 显示页面不存在。您知道是哪里的问题吗？
还有一个问题，文件夹下的python脚本是做什么用的？

**Comment by 13230046860** [comment]
测试环境的openfire版本是Openfire 4.0.2

**Comment by 13230046860** [comment]
大佬在线等

**Comment by htchina** [comment]
留个联系方式，我好发给你

**Comment by 13230046860** [comment]
微信13230046860 邮箱1106627848@qq.com谢谢师傅

**Comment by ddrsk** [comment]
这个可以用冰蝎或者其他工具连接吗

**Comment by uuuuuuzeus** [comment]
q
