### ISSUE TITLE
这个可以用工具连接吗

### ISSUE THREAD

**Issue by ddrsk** [htchina/openfire-webshell#3]
插件上传测试成功了，如何冰蝎这些连接呢

**Comment by htchina** [comment]
你直接用命令在环境里上传个马，然后就可以连接了

**Comment by ddrsk** [comment]
高一点的版本好像不行，比如4.5.0

**Comment by htchina** [comment]
高版本的请自行测试

**Comment by HaoranHanz** [comment]
> 插件上传测试成功了，如何冰蝎这些连接呢

请问你成功了嘛？能否指导一下。

**Comment by HaoranHanz** [comment]
> 高版本的请自行测试

我按照要求上传了jar包，用chrome浏览器打不开http://*.*.*.*:9090/plugins/jcore/married.jsp，显示无法连接。

**Comment by htchina** [comment]
> > 高版本的请自行测试
> 
> 我按照要求上传了jar包，用chrome浏览器打不开http://_._._._:9090/plugins/jcore/married.jsp，显示无法连接。

注意查看图片，可以执行命令，找到相对应的目录上传shell就可以连接

**Comment by HaoranHanz** [comment]
> 不是利用openfire管理页面的jar包上传功能上传到plugins目录下嘛？能否给一个VX，想跟您请教一下，万分感谢。

**Comment by htchina** [comment]
> > 不是利用openfire管理页面的jar包上传功能上传到plugins目录下嘛？能否给一个VX，想跟您请教一下，万分感谢。

把你的留下，我加你

**Comment by HaoranHanz** [comment]
> > > 不是利用openfire管理页面的jar包上传功能上传到plugins目录下嘛？能否给一个VX，想跟您请教一下，万分感谢。
> 
> 把你的留下，我加你

18300285855     Savior_Han_C

**Comment by HaoranHanz** [comment]
> > > > 不是利用openfire管理页面的jar包上传功能上传到plugins目录下嘛？能否给一个VX，想跟您请教一下，万分感谢。
> > 
> > 
> > 把你的留下，我加你
> 
> 手机号：18300285855   VX号：Savior_Han_C

**Comment by HaoranHanz** [comment]
> > > > > 不是利用openfire管理页面的jar包上传功能上传到plugins目录下嘛？能否给一个VX，想跟您请教一下，万分感谢。
> > > 
> > > 
> > > 把你的留下，我加你
> > 
> > 
> > 手机号：18300285855   VX号：Savior_Han_C

万分感谢您能指导。
